// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: yaho.proto

// option go_package = "github.com/KumKeeHyun/grpc-example/heartbeat/yaho";

package yaho

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClaimArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimID   int32  `protobuf:"varint,1,opt,name=claimID,proto3" json:"claimID,omitempty"`
	ClaimAddr string `protobuf:"bytes,2,opt,name=claimAddr,proto3" json:"claimAddr,omitempty"`
}

func (x *ClaimArg) Reset() {
	*x = ClaimArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaho_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimArg) ProtoMessage() {}

func (x *ClaimArg) ProtoReflect() protoreflect.Message {
	mi := &file_yaho_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimArg.ProtoReflect.Descriptor instead.
func (*ClaimArg) Descriptor() ([]byte, []int) {
	return file_yaho_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimArg) GetClaimID() int32 {
	if x != nil {
		return x.ClaimID
	}
	return 0
}

func (x *ClaimArg) GetClaimAddr() string {
	if x != nil {
		return x.ClaimAddr
	}
	return ""
}

type ClaimReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ClaimReply) Reset() {
	*x = ClaimReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaho_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimReply) ProtoMessage() {}

func (x *ClaimReply) ProtoReflect() protoreflect.Message {
	mi := &file_yaho_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimReply.ProtoReflect.Descriptor instead.
func (*ClaimReply) Descriptor() ([]byte, []int) {
	return file_yaho_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPeersArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPeersArg) Reset() {
	*x = GetPeersArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaho_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeersArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersArg) ProtoMessage() {}

func (x *GetPeersArg) ProtoReflect() protoreflect.Message {
	mi := &file_yaho_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersArg.ProtoReflect.Descriptor instead.
func (*GetPeersArg) Descriptor() ([]byte, []int) {
	return file_yaho_proto_rawDescGZIP(), []int{2}
}

type GetPeersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *GetPeersReply) Reset() {
	*x = GetPeersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaho_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersReply) ProtoMessage() {}

func (x *GetPeersReply) ProtoReflect() protoreflect.Message {
	mi := &file_yaho_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersReply.ProtoReflect.Descriptor instead.
func (*GetPeersReply) Descriptor() ([]byte, []int) {
	return file_yaho_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeersReply) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaho_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_yaho_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_yaho_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_yaho_proto protoreflect.FileDescriptor

var file_yaho_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x79, 0x61, 0x68, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x61,
	0x68, 0x6f, 0x22, 0x42, 0x0a, 0x08, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x41, 0x72, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x22, 0x26, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x0d,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x41, 0x72, 0x67, 0x22, 0x31, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20,
	0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x79, 0x61, 0x68, 0x6f, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73,
	0x22, 0x2a, 0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x71, 0x0a, 0x10,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x0e, 0x2e, 0x79, 0x61, 0x68, 0x6f,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x41, 0x72, 0x67, 0x1a, 0x10, 0x2e, 0x79, 0x61, 0x68, 0x6f,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x11, 0x2e, 0x79, 0x61, 0x68, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x41, 0x72, 0x67, 0x1a, 0x13, 0x2e, 0x79, 0x61, 0x68,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yaho_proto_rawDescOnce sync.Once
	file_yaho_proto_rawDescData = file_yaho_proto_rawDesc
)

func file_yaho_proto_rawDescGZIP() []byte {
	file_yaho_proto_rawDescOnce.Do(func() {
		file_yaho_proto_rawDescData = protoimpl.X.CompressGZIP(file_yaho_proto_rawDescData)
	})
	return file_yaho_proto_rawDescData
}

var file_yaho_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yaho_proto_goTypes = []interface{}{
	(*ClaimArg)(nil),      // 0: yaho.ClaimArg
	(*ClaimReply)(nil),    // 1: yaho.ClaimReply
	(*GetPeersArg)(nil),   // 2: yaho.GetPeersArg
	(*GetPeersReply)(nil), // 3: yaho.GetPeersReply
	(*Peer)(nil),          // 4: yaho.Peer
}
var file_yaho_proto_depIdxs = []int32{
	4, // 0: yaho.GetPeersReply.peers:type_name -> yaho.Peer
	0, // 1: yaho.HeartBeatService.Claim:input_type -> yaho.ClaimArg
	2, // 2: yaho.HeartBeatService.GetPeers:input_type -> yaho.GetPeersArg
	1, // 3: yaho.HeartBeatService.Claim:output_type -> yaho.ClaimReply
	3, // 4: yaho.HeartBeatService.GetPeers:output_type -> yaho.GetPeersReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yaho_proto_init() }
func file_yaho_proto_init() {
	if File_yaho_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yaho_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaho_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaho_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeersArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaho_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaho_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yaho_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yaho_proto_goTypes,
		DependencyIndexes: file_yaho_proto_depIdxs,
		MessageInfos:      file_yaho_proto_msgTypes,
	}.Build()
	File_yaho_proto = out.File
	file_yaho_proto_rawDesc = nil
	file_yaho_proto_goTypes = nil
	file_yaho_proto_depIdxs = nil
}
